### ISSUE TITLE
Error when try to start the proxy server (.NET Framework)

### ISSUE THREAD

**Issue by r00tee** [ArachisH/Eavesdrop#28]
When I try to start the proxy server, i get this errors in .NET Framework only

Eavesdropper.Initiate(port)
```
System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at Eavesdrop.INETOptions.Save(String proxyAddress, String autoConfigPath, Boolean isApplyingProxyExplicitly) in /_/Eavesdrop/Native/INETOptions.cs:line 61
   at Eavesdrop.INETOptions.Save(String proxyAddress, String autoConfigPath, Boolean isApplyingProxyExplicitly) in /_/Eavesdrop/Native/INETOptions.cs:line 20
   at Eavesdrop.Eavesdropper.Initiate(Int32 port, Boolean isApplyingProxyExplicitly) in /_/Eavesdrop/Eavesdropper.cs:line 155
   at Change_IP.Form1.Button1_Click(Object sender, EventArgs e) in C:\Users\Nothing\source\repos\Change IP\Change IP\Form1.vb:line 17
```

Eavesdropper.Terminate()
```
System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at Eavesdrop.INETOptions.Save(String proxyAddress, String autoConfigPath, Boolean isApplyingProxyExplicitly) in /_/Eavesdrop/Native/INETOptions.cs:line 61
   at Eavesdrop.Eavesdropper.Terminate() in /_/Eavesdrop/Eavesdropper.cs:line 133
   at Change_IP.Form1.Form1_Closing(Object sender, CancelEventArgs e)
```

**Comment by webbrain-one** [comment]
Thanks for reporting this! I've opened a pull request to address the `Win32Exception` you're encountering when starting and terminating the proxy server on .NET Framework: https://github.com/ArachisH/Eavesdrop/pull/30

This fix corrects how the `INETOptions.Save` method formats its parameters for the .NET Framework runtime, which should resolve the "The parameter is incorrect" error during both `Initiate()` and `Terminate()`. Feel free to test it out and let me know if you run into anything else. Thanks again for the detailed report!
